// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcAEHXsfSwfCHRqESkHEzry5okcfT2j24',
    appId: '1:951844918461:web:5e4865c1598d31448d13d4',
    messagingSenderId: '951844918461',
    projectId: 'zarity-intern',
    authDomain: 'zarity-intern.firebaseapp.com',
    storageBucket: 'zarity-intern.appspot.com',
    measurementId: 'G-0Z6RWNXZGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXp93v0kNRFJHDwuQ_EvrQJVC4xoAg_yw',
    appId: '1:951844918461:android:463917470d6ab7928d13d4',
    messagingSenderId: '951844918461',
    projectId: 'zarity-intern',
    storageBucket: 'zarity-intern.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZX2aRwtQQvKlGXdcOd5yGg0FKB5-OwkE',
    appId: '1:951844918461:ios:0ef0b7fd6187af788d13d4',
    messagingSenderId: '951844918461',
    projectId: 'zarity-intern',
    storageBucket: 'zarity-intern.appspot.com',
    iosClientId: '951844918461-cgk87877qagrteb811vvnh79k67bktos.apps.googleusercontent.com',
    iosBundleId: 'com.example.zarityTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZX2aRwtQQvKlGXdcOd5yGg0FKB5-OwkE',
    appId: '1:951844918461:ios:0ef0b7fd6187af788d13d4',
    messagingSenderId: '951844918461',
    projectId: 'zarity-intern',
    storageBucket: 'zarity-intern.appspot.com',
    iosClientId: '951844918461-cgk87877qagrteb811vvnh79k67bktos.apps.googleusercontent.com',
    iosBundleId: 'com.example.zarityTask',
  );
}
